-- 코드를 입력하세요
SELECT DISTINCT PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) AS SALES
FROM PRODUCT PRO
JOIN OFFLINE_SALE OS ON PRO.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PRO.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC