SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT 
        REST_ID, 
        REST_NAME, 
        FOOD_TYPE, 
        FAVORITES, 
        RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS rank
    FROM REST_INFO
)
WHERE rank = 1
ORDER BY FOOD_TYPE DESC;