SELECT  FLAVOR         
        FROM(
SELECT A.FLAVOR , 
        A.SUM_TOT_1,
        B.SUM_TOT_2,
        (SUM_TOT_1+SUM_TOT_2) AS FINAL_TOTAL        
 FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM_TOT_1
         FROM JULY
        GROUP BY FLAVOR
      ) A
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER)  SUM_TOT_2
                FROM FIRST_HALF
            GROUP BY FLAVOR
           )  B
  ON A.FLAVOR = B.FLAVOR 
  
  ORDER BY FINAL_TOTAL DESC
)  
WHERE ROWNUM < 4