-- 코드를 작성해주세요
WITH YearlyMaxSize AS (
  SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
  FROM ECOLI_DATA
  GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT
  YEAR(e.DIFFERENTIATION_DATE) AS YEAR,
  y.MAX_SIZE - e.SIZE_OF_COLONY AS YEAR_DEV,
  e.ID
FROM ECOLI_DATA e
JOIN YearlyMaxSize y ON YEAR(e.DIFFERENTIATION_DATE) = y.YEAR
ORDER BY YEAR, YEAR_DEV, ID;
