-- 코드를 작성해주세요
WITH MaxFish AS (
  SELECT
    FISH_TYPE,
    MAX(LENGTH) AS MAX_LENGTH
  FROM FISH_INFO
  WHERE LENGTH IS NOT NULL 
  GROUP BY FISH_TYPE
)

SELECT
  fi.ID,
  fni.FISH_NAME,
  fi.LENGTH
FROM FISH_INFO fi
JOIN FISH_NAME_INFO fni ON fi.FISH_TYPE = fni.FISH_TYPE
JOIN MaxFish mf ON fi.FISH_TYPE = mf.FISH_TYPE AND fi.LENGTH = mf.MAX_LENGTH
ORDER BY fi.ID ASC;
